# Netlify Configuration
# Unparalleled Scholar - US.V1

[build]
  publish = "src"
  command = "echo 'No build command required for static frontend'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
